baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Open source suggestions'
theme = 'PaperMod'

[params]
disableSpecial1stPost = true
author = 'luc-git'
description = 'Welcome to the website made for sharing your open source ideas'
[params.profileMode]
enabled = true
subtitle = 'Welcome to the website made for sharing your open source ideas.'
[[params.socialIcons]]
name = 'github'
url = 'https://github.com/open-source-suggestions/ideas.git'
[[params.profileMode.buttons]]
name = 'ideas'
url = './ideas'
[[params.profileMode.buttons]]
name = 'ideas proposal guide'
url = './proposing'

[[menu.main]]
identifier= "proposing"
name= "proposing ideas"
url= "/proposing"
weight= 30
