baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Open source project ideas'
theme = 'PaperMod'

[params]
disableSpecial1stPost = true

[[menu.main]]
identifier= "proposing"
name= "proposing ideas"
url= "/proposing"
weight= 30
