baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Open source project ideas'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


[[menus.main]]
name = 'proposing your idea'
pageRef = '/proposing'

[[menus.main]]
name = 'home'
pageRef = '/'

[[menus.main]]
name = 'contribute to the source code'
pageRef = '/contribute'
