baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Open source project ideas'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


[[menus.main]]
name = 'How to contribute'
pageRef = '/contribute'